### ISSUE TITLE
test

### ISSUE THREAD

**Issue by HelloLiHua** [SmallTeddy/vue-files-preview#1]
阿巴阿巴阿巴阿巴阿巴

**Comment by HelloLiHua** [comment]
代码里的这个Preview是哪来的啊？没看懂
![image](https://github.com/user-attachments/assets/50c0db9e-d33c-4d93-9a33-b994c2387239)

**Comment by SmallTeddy** [comment]
您好 我这边有修改了一个版本 可以看一下
